FROM python:3.7-buster

ARG PYINSTALLER_VERSION=3.6

RUN pip install "pyinstaller==$PYINSTALLER_VERSION"

RUN apt update \
    && apt install -y \
        build-essential \
        software-properties-common \
        wget \
    && apt clean

ENV WINEARCH win64
ENV WINEDEBUG fixme-all
ENV WINEPREFIX /wine
COPY ./windows/install-wine.sh /
RUN /install-wine.sh

COPY ./windows/install-python.sh /
RUN /install-python.sh

# Using windows pip
RUN /bin/bash -c "PATH=/usr/local/bin-wine:\$PATH pip install \"pyinstaller==$PYINSTALLER_VERSION\""
RUN mkdir -p /src/ && ln -s /src /wine/drive_c/src
RUN mkdir -p /tmp/ && ln -s /tmp /wine/drive_c/tmp
WORKDIR /src/
#
#COPY entrypoint-linux.sh /entrypoint.sh
#ENTRYPOINT ["/entrypoint.sh"]
